# Generated by Django 4.2.30 on 2026-06-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_book_readingsession'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='readingsession',
            constraint=models.UniqueConstraint(fields=('user', 'book', 'Date'), name='uniek_leesmoment_per_boek_per_dag'),
        ),
    ]
